import type {
  DashboardDTO,
  DashboardListDTO,
  CreateDashboardRequest,
  UpdateDashboardRequest,
  DataSourceListDTO,
} from './types';

const API_BASE = '/api/vizora';
const FETCH_TIMEOUT = 30000; // 30 seconds timeout for slow SQL Server queries

async function fetchWithTimeout(url: string, options: RequestInit = {}): Promise<Response> {
  const controller = new AbortController();
  const timeoutId = setTimeout(() => controller.abort(), FETCH_TIMEOUT);

  try {
    const response = await fetch(url, {
      ...options,
      signal: controller.signal,
    });
    clearTimeout(timeoutId);
    return response;
  } catch (error) {
    clearTimeout(timeoutId);
    if (error instanceof Error && error.name === 'AbortError') {
      throw new Error(`Request timeout after ${FETCH_TIMEOUT}ms`);
    }
    throw error;
  }
}

async function handleResponse<T>(response: Response): Promise<T> {
  if (!response.ok) {
    const body = await response.text().catch(() => '');
    throw new Error(`API error ${response.status}: ${body || response.statusText}`);
  }
  if (response.status === 204) return undefined as T;
  return response.json();
}

export async function listDashboards(page = 1, pageSize = 20): Promise<DashboardListDTO> {
  const res = await fetchWithTimeout(`${API_BASE}/dashboards?page=${page}&pageSize=${pageSize}`);
  return handleResponse<DashboardListDTO>(res);
}

export async function getDashboard(id: string): Promise<DashboardDTO> {
  const res = await fetchWithTimeout(`${API_BASE}/dashboards/${id}`);
  return handleResponse<DashboardDTO>(res);
}

export async function createDashboard(data: CreateDashboardRequest): Promise<DashboardDTO> {
  const res = await fetchWithTimeout(`${API_BASE}/dashboards`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(data),
  });
  return handleResponse<DashboardDTO>(res);
}

export async function updateDashboard(id: string, data: UpdateDashboardRequest): Promise<DashboardDTO> {
  const res = await fetchWithTimeout(`${API_BASE}/dashboards/${id}`, {
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(data),
  });
  return handleResponse<DashboardDTO>(res);
}

export async function deleteDashboard(id: string): Promise<void> {
  const res = await fetchWithTimeout(`${API_BASE}/dashboards/${id}`, { method: 'DELETE' });
  return handleResponse<void>(res);
}

export async function duplicateDashboard(id: string): Promise<DashboardDTO> {
  const res = await fetchWithTimeout(`${API_BASE}/dashboards/${id}/duplicate`, { method: 'POST' });
  return handleResponse<DashboardDTO>(res);
}

export async function getDataSources(): Promise<DataSourceListDTO> {
  const res = await fetchWithTimeout(`${API_BASE}/data-sources`);
  return handleResponse<DataSourceListDTO>(res);
}

export async function searchTables(
  search: string,
  limit: number = 10,
  offset: number = 0,
): Promise<{ tables: import('./types').TableDTO[]; totalCount: number }> {
  const params = new URLSearchParams({
    search,
    limit: String(limit),
    offset: String(offset),
  });
  const res = await fetchWithTimeout(`${API_BASE}/tables?${params}`);
  return handleResponse(res);
}

export type AutoGenerateResponse = {
  config: import('./types').DashboardConfig;
  isPartial: boolean;
};

export async function autoGenerateDashboard(tableName: string): Promise<AutoGenerateResponse> {
  const res = await fetchWithTimeout(`${API_BASE}/auto-generate`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ tableName }),
  });
  return handleResponse<AutoGenerateResponse>(res);
}

export async function getTableSchema(tableName: string): Promise<{ columns: import('./types').ColumnDTO[] }> {
  const res = await fetchWithTimeout(`${API_BASE}/table-schema/${encodeURIComponent(tableName)}`);
  return handleResponse(res);
}

export async function getDistinctValues(
  table: string,
  column: string,
  limit: number = 100,
): Promise<{ values: unknown[]; count: number }> {
  const params = new URLSearchParams({ table, column, limit: String(limit) });
  const res = await fetchWithTimeout(`${API_BASE}/distinct-values?${params}`);
  return handleResponse(res);
}

export async function getNumericBounds(
  table: string,
  column: string,
): Promise<{ min: number | null; max: number | null }> {
  const params = new URLSearchParams({ table, column });
  const res = await fetchWithTimeout(`${API_BASE}/numeric-bounds?${params}`);
  return handleResponse(res);
}
