'use client';

import { useState, useCallback, useEffect, useRef } from 'react';
import { useRouter } from 'next/navigation';
import { cn } from '@/lib/utils';
import { Sparkles, X, Loader2, Table2, Search, ChevronLeft, ChevronRight } from 'lucide-react';
import { searchTables, autoGenerateDashboard, createDashboard } from '@/lib/vizora/dashboard-api';
import type { TableDTO } from '@/lib/vizora/types';

const PAGE_SIZE = 10;

export default function AutoGenerateDialog() {
  const router = useRouter();
  const [open, setOpen] = useState(false);
  const [step, setStep] = useState<'select' | 'loading' | 'error'>('select');
  const [tables, setTables] = useState<TableDTO[]>([]);
  const [selectedTable, setSelectedTable] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [loadingTables, setLoadingTables] = useState(false);
  const [searchQuery, setSearchQuery] = useState('');
  const [totalCount, setTotalCount] = useState(0);
  const [currentPage, setCurrentPage] = useState(0);
  const [pageNumberInput, setPageNumberInput] = useState('1');
  const searchTimeoutRef = useRef<NodeJS.Timeout | null>(null);

  const totalPages = Math.ceil(totalCount / PAGE_SIZE);

  const loadTables = useCallback(async (search: string, page: number) => {
    setLoadingTables(true);
    setError(null);
    try {
      const result = await searchTables(search, PAGE_SIZE, page * PAGE_SIZE);
      setTables(result.tables);
      setTotalCount(result.totalCount);
      setCurrentPage(page);
    } catch {
      setError('Failed to load tables');
      setTables([]);
      setTotalCount(0);
    } finally {
      setLoadingTables(false);
    }
  }, []);

  const openDialog = useCallback(() => {
    setOpen(true);
    setStep('select');
    setError(null);
    setSelectedTable(null);
    setSearchQuery('');
    setCurrentPage(0);
    setPageNumberInput('1');
    loadTables('', 0);
  }, [loadTables]);

  const handleSearchChange = useCallback((value: string) => {
    setSearchQuery(value);
    setCurrentPage(0);
    setSelectedTable(null);

    if (searchTimeoutRef.current) {
      clearTimeout(searchTimeoutRef.current);
    }

    searchTimeoutRef.current = setTimeout(() => {
      loadTables(value, 0);
    }, 300);
  }, [loadTables]);

  const handlePageChange = useCallback((newPage: number) => {
    setCurrentPage(newPage);
    setSelectedTable(null);
    setPageNumberInput(String(newPage + 1));
    loadTables(searchQuery, newPage);
  }, [searchQuery, loadTables]);

  const handleJumpToPage = useCallback(() => {
    const page = parseInt(pageNumberInput, 10);
    if (isNaN(page) || page < 1 || page > totalPages) {
      setPageNumberInput(String(currentPage + 1));
      return;
    }
    handlePageChange(page - 1);
  }, [pageNumberInput, totalPages, currentPage, handlePageChange]);

  const handleGenerate = useCallback(async () => {
    if (!selectedTable) return;
    setStep('loading');
    setError(null);
    try {
      const { config } = await autoGenerateDashboard(selectedTable);
      const dashboard = await createDashboard({
        name: `Auto: ${selectedTable}`,
        description: `Auto-generated dashboard for ${selectedTable}`,
        config,
      });
      setOpen(false);
      router.push(`/vizora/dashboards/${dashboard.id}`);
    } catch (err) {
      setStep('error');
      setError(err instanceof Error ? err.message : 'Generation failed');
    }
  }, [selectedTable, router]);

  useEffect(() => {
    return () => {
      if (searchTimeoutRef.current) {
        clearTimeout(searchTimeoutRef.current);
      }
    };
  }, []);

  return (
    <>
      <button
        data-auto-generate
        onClick={openDialog}
        className={cn(
          'inline-flex items-center gap-2 rounded-xl bg-gradient-to-r from-violet-600 to-purple-600 px-5 py-2.5 text-sm font-semibold',
          'text-white shadow-lg shadow-violet-500/25 transition-all hover:shadow-xl hover:-translate-y-0.5',
        )}
      >
        <Sparkles className="h-4 w-4" />
        Auto-generate
      </button>

      {open && (
        <div className="fixed inset-0 z-50 flex items-center justify-center">
          <div className="fixed inset-0 bg-black/40" onClick={() => setOpen(false)} />
          <div className="relative z-10 flex w-full max-w-2xl flex-col gap-4 rounded-2xl border border-border bg-card p-6 shadow-lg">
            <div className="flex items-center justify-between">
              <h2 className="text-lg font-semibold text-foreground">Auto-generate Dashboard</h2>
              <button onClick={() => setOpen(false)} className="rounded-lg p-1 text-muted-foreground hover:bg-accent">
                <X className="h-4 w-4" />
              </button>
            </div>

            {step === 'select' && (
              <>
                <div className="space-y-3">
                  <div className="relative">
                    <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
                    <input
                      type="text"
                      value={searchQuery}
                      onChange={(e) => handleSearchChange(e.target.value)}
                      placeholder="Search tables by name..."
                      className={cn(
                        'w-full rounded-lg border border-input bg-background py-2.5 pl-10 pr-4 text-sm text-foreground',
                        'placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-ring',
                      )}
                    />
                  </div>

                  {loadingTables ? (
                    <div className="flex items-center justify-center py-12">
                      <Loader2 className="h-5 w-5 animate-spin text-muted-foreground" />
                    </div>
                  ) : (
                    <>
                      <div className="max-h-96 overflow-y-auto rounded-lg border border-border">
                        {tables.length === 0 ? (
                          <div className="flex flex-col items-center justify-center py-12 text-center">
                            <Table2 className="h-8 w-8 text-muted-foreground/40 mb-2" />
                            <p className="text-sm text-muted-foreground">
                              {searchQuery ? 'No tables found' : 'No tables available'}
                            </p>
                          </div>
                        ) : (
                          tables.map((t) => (
                            <button
                              key={`${t.tableSchema}.${t.tableName}`}
                              onClick={() => setSelectedTable(t.tableName)}
                              className={cn(
                                'flex w-full items-center gap-3 px-4 py-3 text-left text-sm transition-colors border-b border-border last:border-b-0',
                                'hover:bg-accent',
                                selectedTable === t.tableName && 'bg-accent',
                              )}
                            >
                              <Table2 className="h-4 w-4 shrink-0 text-muted-foreground" />
                              <div className="min-w-0 flex-1">
                                <p className="truncate font-medium text-foreground">{t.tableName}</p>
                                <p className="text-xs text-muted-foreground">
                                  {t.tableSchema} &middot; ~{Number(t.rowCountEstimate).toLocaleString()} rows
                                </p>
                              </div>
                            </button>
                          ))
                        )}
                      </div>

                      {totalCount > PAGE_SIZE && (
                        <div className="flex items-center justify-between px-2">
                          <p className="text-xs text-muted-foreground">
                            Showing {currentPage * PAGE_SIZE + 1}-{Math.min((currentPage + 1) * PAGE_SIZE, totalCount)} of {totalCount} tables
                          </p>
                          <div className="flex items-center gap-2">
                            <button
                              onClick={() => handlePageChange(currentPage - 1)}
                              disabled={currentPage === 0}
                              className={cn(
                                'inline-flex items-center gap-1 rounded-lg px-3 py-1.5 text-xs font-medium',
                                'text-foreground/70 transition-colors hover:bg-accent',
                                'disabled:cursor-not-allowed disabled:opacity-50',
                              )}
                            >
                              <ChevronLeft className="h-3 w-3" />
                              Previous
                            </button>
                            
                            <div className="flex items-center gap-1.5">
                              <span className="text-xs text-muted-foreground">Page</span>
                              <input
                                type="number"
                                min={1}
                                max={totalPages}
                                value={pageNumberInput}
                                onChange={(e) => setPageNumberInput(e.target.value)}
                                onBlur={handleJumpToPage}
                                onKeyDown={(e) => {
                                  if (e.key === 'Enter') {
                                    e.preventDefault();
                                    handleJumpToPage();
                                  }
                                }}
                                className="w-16 rounded-md border border-border bg-background px-2 py-1 text-center text-xs font-medium text-foreground outline-none focus:border-primary focus:ring-1 focus:ring-primary"
                              />
                              <span className="text-xs text-muted-foreground">of {totalPages}</span>
                            </div>

                            <button
                              onClick={() => handlePageChange(currentPage + 1)}
                              disabled={currentPage >= totalPages - 1}
                              className={cn(
                                'inline-flex items-center gap-1 rounded-lg px-3 py-1.5 text-xs font-medium',
                                'text-foreground/70 transition-colors hover:bg-accent',
                                'disabled:cursor-not-allowed disabled:opacity-50',
                              )}
                            >
                              Next
                              <ChevronRight className="h-3 w-3" />
                            </button>
                          </div>
                        </div>
                      )}
                    </>
                  )}
                </div>

                {error && (
                  <p className="text-sm text-destructive">{error}</p>
                )}

                <div className="flex justify-end gap-2 pt-2">
                  <button
                    onClick={() => setOpen(false)}
                    className="rounded-lg px-4 py-2 text-sm font-medium text-muted-foreground hover:bg-accent"
                  >
                    Cancel
                  </button>
                  <button
                    onClick={handleGenerate}
                    disabled={!selectedTable}
                    className={cn(
                      'rounded-lg px-4 py-2 text-sm font-medium text-white transition-colors',
                      selectedTable ? 'bg-violet-600 hover:bg-violet-700' : 'cursor-not-allowed bg-violet-600/50',
                    )}
                  >
                    Generate
                  </button>
                </div>
              </>
            )}

            {step === 'loading' && (
              <div className="flex flex-col items-center gap-3 py-12">
                <Loader2 className="h-6 w-6 animate-spin text-violet-600" />
                <p className="text-sm text-muted-foreground">
                  Generating dashboard for <span className="font-medium text-foreground">{selectedTable}</span>...
                </p>
              </div>
            )}

            {step === 'error' && (
              <>
                <p className="text-sm text-destructive">{error}</p>
                <div className="flex justify-end gap-2">
                  <button
                    onClick={() => { setStep('select'); setError(null); }}
                    className="rounded-lg px-4 py-2 text-sm font-medium text-muted-foreground hover:bg-accent"
                  >
                    Try again
                  </button>
                  <button
                    onClick={() => setOpen(false)}
                    className="rounded-lg px-4 py-2 text-sm font-medium text-foreground hover:bg-accent"
                  >
                    Close
                  </button>
                </div>
              </>
            )}
          </div>
        </div>
      )}
    </>
  );
}
