import { Suspense } from 'react';
import DashboardList from '@/components/vizora/dashboard-list';
import { DashboardListSkeleton } from '@/components/vizora/skeletons/DashboardListSkeleton';
import AutoGenerateDialog from '@/components/vizora/auto-generate-dialog';
import { Plus, Sparkles, BarChart3, Zap } from 'lucide-react';
import { cn } from '@/lib/utils';

export default function DashboardsPage() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 via-white to-blue-50/30">
      {/* Header Banner */}
      <div className="relative overflow-hidden border-b border-slate-200/60 bg-gradient-to-r from-slate-900 via-slate-800 to-slate-900">
        <div className="pointer-events-none absolute inset-0">
          <div className="absolute -top-24 -right-24 h-64 w-64 rounded-full bg-blue-500/10 blur-3xl" />
          <div className="absolute -bottom-24 -left-24 h-64 w-64 rounded-full bg-indigo-500/10 blur-3xl" />
        </div>
        
        <div className="relative mx-auto max-w-[1600px] px-6 py-10 lg:px-10">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-4">
              <div className="flex h-14 w-14 items-center justify-center rounded-2xl bg-gradient-to-br from-blue-500 to-indigo-600 shadow-lg shadow-blue-500/20">
                <BarChart3 className="h-7 w-7 text-white" />
              </div>
              <div>
                <h1 className="text-3xl font-bold tracking-tight text-white">Dashboards</h1>
                <p className="mt-1 text-sm text-slate-400">Create and manage your interactive dashboards</p>
              </div>
            </div>
            
            <div className="flex items-center gap-3">
              <AutoGenerateDialog />
              <a
                href="/vizora/dashboards/new"
                className={cn(
                  'inline-flex items-center gap-2 rounded-xl bg-white px-5 py-2.5 text-sm font-semibold',
                  'text-slate-900 shadow-lg shadow-black/10 transition-all hover:shadow-xl hover:-translate-y-0.5',
                )}
              >
                <Plus className="h-4 w-4" />
                Create Dashboard
              </a>
            </div>
          </div>
        </div>
      </div>

      {/* Main Content */}
      <main className="mx-auto max-w-[1600px] px-6 py-8 lg:px-10">
        <Suspense fallback={<DashboardListSkeleton />}>
          <DashboardList />
        </Suspense>
      </main>
    </div>
  );
}
