import { Suspense } from 'react';
import DashboardList from '@/components/vizora/dashboard-list';
import { DashboardListSkeleton } from '@/components/vizora/skeletons/DashboardListSkeleton';
import AutoGenerateDialog from '@/components/vizora/auto-generate-dialog';
import { Plus, BarChart3 } from 'lucide-react';
import { cn } from '@/lib/utils';

export default function DashboardsPage() {
  return (
    <div className="min-h-screen bg-slate-50">
      {/* Header Banner - ATLAS Style */}
      <div className="relative overflow-hidden border-b border-teal-700 bg-teal-600">
        <div className="relative mx-auto max-w-[1600px] px-6 py-8 lg:px-10">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-4">
              <div className="flex h-12 w-12 items-center justify-center rounded-lg bg-white/10">
                <BarChart3 className="h-6 w-6 text-white" />
              </div>
              <div>
                <h1 className="text-2xl font-bold text-white">Dashboards</h1>
                <p className="mt-0.5 text-sm text-teal-100">Create and manage your interactive dashboards</p>
              </div>
            </div>
            
            <div className="flex items-center gap-3">
              <AutoGenerateDialog />
              <a
                href="/vizora/dashboards/new"
                className={cn(
                  'inline-flex items-center gap-2 rounded-lg bg-white px-5 py-2.5 text-sm font-semibold',
                  'text-teal-700 shadow-sm transition-all hover:bg-teal-50 hover:shadow-md hover:-translate-y-0.5',
                )}
              >
                <Plus className="h-4 w-4" />
                Create Dashboard
              </a>
            </div>
          </div>
        </div>
      </div>

      {/* Main Content */}
      <main className="mx-auto max-w-[1600px] px-6 py-8 lg:px-10">
        <Suspense fallback={<DashboardListSkeleton />}>
          <DashboardList />
        </Suspense>
      </main>
    </div>
  );
}
