import { Suspense } from 'react';
import DashboardList from '@/components/vizora/dashboard-list';
import { DashboardListSkeleton } from '@/components/vizora/skeletons/DashboardListSkeleton';
import AutoGenerateDialog from '@/components/vizora/auto-generate-dialog';
import { Plus } from 'lucide-react';
import { cn } from '@/lib/utils';

export default function DashboardsPage() {
  return (
    <div className="min-h-screen bg-background">
      <main className="mx-auto flex max-w-[1600px] flex-col gap-6 px-6 py-8 lg:px-10">
        <div className="flex items-center justify-between">
          <div>
            <h1 className="text-2xl font-bold text-foreground">Dashboards</h1>
            <p className="text-sm text-muted-foreground">Create and manage your interactive dashboards</p>
          </div>
          <div className="flex items-center gap-3">
            <AutoGenerateDialog />
            <a
              href="/vizora/dashboards/new"
              className={cn(
                'inline-flex items-center gap-2 rounded-xl bg-primary px-4 py-2.5 text-sm font-medium',
                'text-primary-foreground shadow-soft transition-colors hover:bg-primary/90',
              )}
            >
              <Plus className="h-4 w-4" />
              Create Dashboard
            </a>
          </div>
        </div>
        <Suspense fallback={<DashboardListSkeleton />}>
          <DashboardList />
        </Suspense>
      </main>
    </div>
  );
}
